### ISSUE TITLE
Mint contract - Price Slippage Revert Contract

### ISSUE THREAD

**Issue by AustinWoetzel** [securesecrets/shade#12]
Front end app inputs a minimum quantity of Silk the user should receive in the transaction (via user entered slippage % tolerance) based on calculations done on the front end from an Oracle price query. If the Silk qty received drops below the minimum by the time the transaction is processed, then the transaction is cancelled, no SILK is received and no sSCRT is burned.

**Comment by mohammedpatla** [comment]
This is important for peg
