### ISSUE TITLE
Airdrop IBC wallet permits

### ISSUE THREAD

**Issue by FloppyDisck** [securesecrets/shade#140]
**Is your feature request related to a problem? Please describe.**
Non SCRT wallets cannot interact with the contract

**Describe the solution you'd like**
Before redeeming, users can initialize their airdrop amount by calling an init handle and providing signed permits for each added account as an argument. This would unify all those airdrop accounts into one secret address that could then be used to redeem the airdrop.

Each permit can contain an address and a signature pertaining to that address to prove the user owns it.

**Describe alternatives you've considered**
* IBC addresses interacting with the contract; the problem with this is that IBC with smart contract has not been added yet
* Deriving addresses before the airdrop starts, this is also an issue because we cant derive all of the potential addresses

**Comment by mohammedpatla** [comment]
Yes, I think this is the only solution we have to verify the drops to the correct users.
