### ISSUE TITLE
Security bug: governance:try_fund_proposal doesn't check token origin

### ISSUE THREAD

**Issue by HarryR** [securesecrets/shade#200]
Anybody can call the `try_fund_proposal` function as it doesn't verify the message origin is `config.funding_token`, this allows an attack which could drain all `funding_token` by specifying an arbitrary amount and having the excess refunded to the caller.

https://github.com/securesecrets/shade/blob/main/contracts/governance/src/contract.rs#L76

https://github.com/securesecrets/shade/blob/main/contracts/governance/src/handle.rs#L95

**Comment by FloppyDisck** [comment]
No worries, this is an old version of governance

It was there to prove that some ideas work and is already being replaced by a new governance model
