### ISSUE TITLE
Derivatives:  After Staking SCRT, SCRT gone, no stkd-SCRT credited

### ISSUE THREAD

**Issue by djesys** [securesecrets/shade#386]
Guys,

the title explains it. I just wanted to stake SCRT. Received and error and now I have neither SCRT nor stkd-SCRT !
This is quite serious for me.
The failed transactions is this one:

https://atomscan.com/secret-network/transactions/2183982FD3D4E3ED9E2C49C4377639270A1FC846A3E9FEA9CA02D388C1B25E19

Interestingly stkd-SCRT with a balance of ZERO appeared in my Keplr Token list.

<img width="341" alt="Screenshot 2023-12-04 at 19 38 27" src="https://github.com/securesecrets/shade/assets/4517954/71b22834-03b3-410d-a239-b697c51f2aff">

**Comment by mohammedpatla** [comment]
@djesys this could be due to multiple reasons. Can you connect on our discord help channels admins will be able to help you better.

https://discord.gg/xu6db6n6
