### ISSUE TITLE
Treasury Implementation for Synthesis 

### ISSUE THREAD

**Issue by mohammedpatla** [securesecrets/shade#46]
We need to take % of burned assets and store it in the Governance Treasury.
This is linked to the Governance treasury we would have.

Treasury : https://github.com/securesecrets/shade/issues/48

**Comment by mohammedpatla** [comment]
Jack you already have this going in the last PR i know you have to Test this still.

**Comment by DrPresident** [comment]
This is working with the capture in mint, a specific burned asset has a specific capture amount that will be sent to treasury. As-is mint can handle any snip20 asset and so can treasury so it just comes down to configuration.
