### ISSUE TITLE
Treasury Contract.

### ISSUE THREAD

**Issue by mohammedpatla** [securesecrets/shade#48]
This is a treasury contract for the SHADE protocol.

- [x] Hold any SNIP20 or IBC assets on its sheet.
- [ ] Ability drop, add to the treasuery
- [ ] Some security primates, on hard caps on how much % of tokens can move per day/month

**Comment by FloppyDisck** [comment]
Broke issues into multiple that can be found in https://github.com/securesecrets/shade/projects/3
