### ISSUE TITLE
improve shade_protocol naming

### ISSUE THREAD

**Issue by FloppyDisck** [securesecrets/shade#74]
Currently all the protocol packages have the same init, handle and query variable name and can result into messy code when using multiple (see contract initializer). They should be renamed into contractNameInit,Handle and Query

**Comment by DrPresident** [comment]
I like the current naming scheme, the context implies that it is the init for the oracle, `oracle::InitMsg`. IMO it is unnecessarily verbose to use `oracle::oracleInitMsg`
