### ISSUE TITLE
Secondary Burn Mechanism

### ISSUE THREAD

**Issue by DrPresident** [securesecrets/shade#77]
Burned tokens will be burned with the SNIP-20 burn method when it is available, however if the asset is not burnable (SSCRT) we need a secondary method to destroy the tokens. Some kind of "trash" address we can dump them to will be needed, currently non-burnable tokens just sit on the mint contract.

**Comment by mohammedpatla** [comment]
Yes following better design.

We need to see if their is 0x0000000000 Address like the ETH burn address
