### ISSUE TITLE
Only commission on entry burn

### ISSUE THREAD

**Issue by DrPresident** [securesecrets/shade#78]
Currently the mint contract has 1 commission rate for all burns, we only want to take commission to treasury when we burn certain assets. Each asset should be registered with an optional commission rate, defaulting to 0 (no commission)

Example:
SSCRT -> SILK -- We want %50 SSCRT to treasury
SHD -> SILK -- No commission taken for conversion minting

**Comment by FloppyDisck** [comment]
This could be solved by removing the commission from config and moving it into a value stored per asset
