### ISSUE TITLE
Un-register SecretSwap Pair

### ISSUE THREAD

**Issue by DrPresident** [securesecrets/shade#79]
After registering a Pair for say SETH, there is currently no way to undo this and `get_price(SETH)` will always query secretswap, in the case of a misconfig or an asset we no longer want to support there should be a method to remove/invalidate that secretswap pair with an authorized message.

**Comment by mohammedpatla** [comment]
Oh so we are stuck with Secret Swap once set

**Comment by DrPresident** [comment]
For example currently if you were to register the `SHD/SSCRT` pair for the SHD price feed, there is no way to undo this action. Its simple to add in the removal function but I think it will be important for re-configuration.
