### ISSUE TITLE
SCRT Staking Treasury

### ISSUE THREAD

**Issue by DrPresident** [securesecrets/shade#92]
We want to stake the shade protocol's captured sSCRT as SCRT. This will generate revenue for shade holders and grow the treasury. 
- Configured with a percentage of assets to stake
- Convert sSCRT to SCRT to stake
- Trade other assets to SCRT to stake <- lower priority
- The staked node will be chosen given a set of parameters, semi-randomized to minimize bias

**Comment by rigwild** [comment]
> The staked node will be chosen given a set of parameters, semi-randomized to minimize bias
Wouldn't it make sense to stake to `securesecrets.org` node? Or create a new validator specific for Shade?
